import { assertSafePlainText } from './sanitize';

export type SeoOverrideInput = {
  /** Must match a real public path exactly, e.g. '/services/penetration-testing/'. */
  path: string;
  title?: string | null;
  description?: string | null;
  canonicalUrl?: string | null;
  robotsDirective?: string | null;
};

export class InvalidSeoOverrideError extends Error {}

// Matches the real site's path convention (lowercase, trailing slash, no
// query/fragment) — this is a merge key into a JSON object, not a page the
// override can create, so there's no risk of spinning up a new indexable
// URL from here; see docs/ADMIN_PUBLIC_SITE_INTEGRATION.md.
const PATH_PATTERN = /^\/$|^\/[a-z0-9-]+(\/[a-z0-9-]+)*\/$/;

/**
 * Merges one SEO override into the existing generated-overrides JSON file's
 * content and returns the new file content to commit. Takes the existing
 * file's content as a plain string (fetched by the caller via the GitHub
 * Contents API) rather than doing any I/O itself, so this merge logic is
 * pure and unit-testable. An override with every field empty removes that
 * path's entry entirely, restoring the page's original code-controlled
 * title/description/canonical/robots.
 */
export function buildSeoOverridesFile(existingFileContent: string, override: SeoOverrideInput): string {
  if (!PATH_PATTERN.test(override.path)) {
    throw new InvalidSeoOverrideError(`Path "${override.path}" must be an absolute, lowercase, trailing-slash path.`);
  }
  if (override.title) assertSafePlainText(override.title, 'Title');
  if (override.description) assertSafePlainText(override.description, 'Description');
  if (override.canonicalUrl) assertSafePlainText(override.canonicalUrl, 'Canonical URL');
  if (override.robotsDirective) assertSafePlainText(override.robotsDirective, 'Robots directive');

  let parsed: { overrides?: Record<string, unknown> };
  try {
    parsed = JSON.parse(existingFileContent) as { overrides?: Record<string, unknown> };
  } catch {
    throw new InvalidSeoOverrideError(
      'Existing seo-overrides.generated.json is not valid JSON — refusing to overwrite it blindly.',
    );
  }

  const overrides = { ...(parsed.overrides ?? {}) };
  const entry: Record<string, string> = {};
  if (override.title) entry.title = override.title;
  if (override.description) entry.description = override.description;
  if (override.canonicalUrl) entry.canonicalUrl = override.canonicalUrl;
  if (override.robotsDirective) entry.robotsDirective = override.robotsDirective;

  if (Object.keys(entry).length === 0) {
    delete overrides[override.path];
  } else {
    overrides[override.path] = entry;
  }

  const result = {
    _comment:
      "Generated by apps/admin's SEO publish action (src/lib/publish/renderSeoOverrides.ts) — do not hand-edit. Empty object means no overrides are published yet; every page keeps its own existing title/description/canonical/robots. See docs/ADMIN_PUBLIC_SITE_INTEGRATION.md.",
    overrides,
  };
  return `${JSON.stringify(result, null, 2)}\n`;
}
