import { boolean, datetime, decimal, int, json, mysqlEnum, mysqlTable, text, varchar } from 'drizzle-orm/mysql-core';
import { idColumn, fkColumn } from './columns';

/**
 * A lead is any inbound contact/interest signal — currently generated by
 * the Astro site's public/api/contact.php form, and by this admin app's
 * own public-facing intake once/if it gets one. This table is the
 * canonical record either way; the PHP handler writes here over HTTP
 * (via a narrow, authenticated internal API route) rather than directly
 * to this database, since the static site has no server-side DB access
 * of its own.
 */
export const leads = mysqlTable('leads', {
  id: idColumn(),
  fullName: text('full_name').notNull(),
  // Nullable: a lead created from the booking form (book.php) genuinely
  // never collects an email — see the consultations table's comment.
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  company: text('company'),
  message: text('message'),
  source: varchar('source', { length: 100 }),
  status: mysqlEnum('status', ['new', 'contacted', 'qualified', 'converted', 'lost']).notNull().default('new'),
  assignedToUserId: fkColumn('assigned_to_user_id'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
  updatedAt: datetime('updated_at').notNull().$defaultFn(() => new Date()),
});

/**
 * Booking requests from the Astro site's native booking system
 * (public/api/book.php), mirrored here for admin visibility/workflow —
 * same cross-boundary reasoning as `leads` above. Email is nullable
 * because book.php genuinely never collects one (by its own documented
 * design — confirmation happens over phone/WhatsApp), not an oversight.
 */
export const consultations = mysqlTable('consultations', {
  id: idColumn(),
  leadId: fkColumn('lead_id'),
  fullName: text('full_name').notNull(),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  // Free text, not an ISO code — book.php collects "Please enter your
  // country" as an open text field, not a country-code picker.
  country: varchar('country', { length: 100 }),
  requestedAt: datetime('requested_at').notNull(),
  status: mysqlEnum('status', ['requested', 'confirmed', 'completed', 'cancelled', 'no_show']).notNull().default('requested'),
  notes: text('notes'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

export const customers = mysqlTable('customers', {
  id: idColumn(),
  fullName: text('full_name').notNull(),
  // Nullable: a customer converted from a booking-only lead (see leads'
  // schema comment) genuinely has no email on file.
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }),
  company: text('company'),
  convertedFromLeadId: fkColumn('converted_from_lead_id'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

/**
 * Review requests sent to real customers after a real engagement — the
 * link generated always points at the business's actual Google Business
 * Profile review URL. This table tracks who was asked and when; it never
 * stores or fabricates the review content itself, which lives on Google,
 * not here.
 */
export const reviewRequests = mysqlTable('review_requests', {
  id: idColumn(),
  customerId: fkColumn('customer_id').notNull(),
  requestedByUserId: fkColumn('requested_by_user_id'),
  sentAt: datetime('sent_at').notNull().$defaultFn(() => new Date()),
  status: mysqlEnum('status', ['sent', 'completed', 'declined']).notNull().default('sent'),
});

/**
 * Genuine testimonials only — collected from real clients. `verified`
 * distinguishes a testimonial the business has independently confirmed
 * (e.g. a linked, checkable Google review) from one submitted directly
 * but not yet cross-checked; both must be real, never invented.
 */
export const testimonials = mysqlTable('testimonials', {
  id: idColumn(),
  customerId: fkColumn('customer_id'),
  authorName: text('author_name').notNull(),
  quote: text('quote').notNull(),
  sourceUrl: text('source_url'),
  verificationStatus: mysqlEnum('verification_status', ['pending', 'verified', 'unverified']).notNull().default('pending'),
  status: mysqlEnum('status', ['draft', 'published']).notNull().default('draft'),
  createdByUserId: fkColumn('created_by_user_id'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

export const paymentMethods = mysqlTable('payment_methods', {
  id: idColumn(),
  // Never raw card data — a payment provider's own tokenized
  // reference/method id only (e.g. a Stripe PaymentMethod id).
  provider: varchar('provider', { length: 50 }).notNull(),
  providerMethodRef: text('provider_method_ref').notNull(),
  customerId: fkColumn('customer_id').notNull(),
  label: text('label'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

export const invoices = mysqlTable('invoices', {
  id: idColumn(),
  customerId: fkColumn('customer_id').notNull(),
  invoiceNumber: varchar('invoice_number', { length: 50 }).notNull().unique(),
  currency: varchar('currency', { length: 3 }).notNull().default('USD'),
  amountDue: decimal('amount_due', { precision: 10, scale: 2 }).notNull(),
  status: mysqlEnum('status', ['draft', 'sent', 'paid', 'void', 'overdue']).notNull().default('draft'),
  dueDate: datetime('due_date'),
  createdByUserId: fkColumn('created_by_user_id'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

/**
 * Provider-abstracted: `provider` names which real gateway processed it
 * (or 'manual' for a bank transfer recorded by hand), and no payment
 * provider is wired to live credentials in code until the user supplies
 * real ones — see docs/PAYMENTS.md once written.
 */
export const payments = mysqlTable('payments', {
  id: idColumn(),
  invoiceId: fkColumn('invoice_id'),
  customerId: fkColumn('customer_id').notNull(),
  provider: varchar('provider', { length: 50 }).notNull(),
  providerPaymentRef: text('provider_payment_ref'),
  amount: decimal('amount', { precision: 10, scale: 2 }).notNull(),
  currency: varchar('currency', { length: 3 }).notNull().default('USD'),
  status: mysqlEnum('status', ['pending', 'succeeded', 'failed', 'refunded']).notNull().default('pending'),
  metadata: json('metadata').$type<Record<string, unknown>>(),
  recordedByUserId: fkColumn('recorded_by_user_id'),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

/**
 * Admin-configurable manual payment options (bank transfer, crypto
 * wallet, etc.) shown to staff when recording a payment by hand — same
 * shape and purpose as apps/learn's payment_methods table (a deliberate
 * naming distinction: this app's existing `paymentMethods` table above
 * is unrelated scaffolding for a tokenized gateway reference, not this
 * concept). Not surfaced to the public; shahidiqbal.com has no
 * self-serve checkout of its own.
 */
export const manualPaymentMethods = mysqlTable('manual_payment_methods', {
  id: idColumn(),
  name: text('name').notNull(),
  type: mysqlEnum('type', ['bank_transfer', 'crypto', 'mobile_wallet', 'other']).notNull(),
  instructions: text('instructions'),
  walletAddress: text('wallet_address'),
  isActive: boolean('is_active').notNull().default(true),
  sortOrder: int('sort_order').notNull().default(0),
  createdAt: datetime('created_at').notNull().$defaultFn(() => new Date()),
});

export type Lead = typeof leads.$inferSelect;
export type Consultation = typeof consultations.$inferSelect;
export type Testimonial = typeof testimonials.$inferSelect;
export type ManualPaymentMethod = typeof manualPaymentMethods.$inferSelect;
